services:
  - type: web
    name: erms-backend
    runtime: docker
    rootDir: erms2-backend
    plan: free
    buildCommand: "chmod +x mvnw && ./mvnw clean install"
    startCommand: "java -jar target/*.jar"
